name: "Nightly E2E run"
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  run-tests:
    uses: cosmos/gaia/.github/workflows/test.yml@0d9f7dc938e96c041cc04a51659da6f3907fd9f9 # main

  run-simulations:
    uses: cosmos/gaia/.github/workflows/sims.yml@0d9f7dc938e96c041cc04a51659da6f3907fd9f9 # main

    
